function prettify()
% Makes things less ugly. 
%
% @See https://blogs.mathworks.com/loren/2007/12/11/making-pretty-graphs/

  set(gca, ...
    'Box'         , 'off'     , ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'on'      , ...
    'YMinorTick'  , 'on'      , ...
    'YGrid'       , 'off'     , ...
    'XColor'      , [.3 .3 .3], ...
    'YColor'      , [.3 .3 .3], ...
    'FontName'    , 'Helvetica');
end